### ISSUE TITLE
astro-m2dx not activated

### ISSUE THREAD

**Issue by sebastian-1783** [christian-hackyourshack/npm#25]
Hi, 
need some help, because I can't het astro-m2dx activated in my Astro project (based on the AstroWind theme with MDX support activated already). 

I followed all instructions:
1. Installed astro-m2dx package
2. in astro.config.mjs 
- added the import: import m2dx from 'astro-m2dx';
- added the options object to active the relative images feature which I want to use:
```
const m2dxOptions = {
  relativeImages: true,
};
```
- added the following in the markdown section
```
  markdown: {
    remarkPlugins: [
      remarkReadingTime,
      [m2dx, m2dxOptions]
    ],
    extendDefaultPlugins: true,
    ....
```
3. Created a mdx page in the project with code to include an image with relative path to image located in the same folder:
```
# This is a MDX test page
![My alt text](img01.jpg 'Title of Image')
```

Result: Image is not displayed.

Is there anything which I missed in getting the relative image feature of astro-m2dx activated for my MDX files?

Thanks!

**Comment by christian-hackyourshack** [comment]
Just a few points to poke around:

- which version of astro-m2dx are you using?
- add an empty line above your image (otherwise it might be part of the h1)
- reference your image using ./img01.jpg (usually just necessary if you want relative images resolved in arbitrary element attributes)

**Comment by sebastian-1783** [comment]
Thanks so much for your help!

Version according to my package.json: "astro-m2dx": "^0.4.6"

I have added the empty line between headline and image and I changed to `![My alt text](./img01.jpg 'Title of Image')` 
However no success so for, image is still not displayed. 

By the way, both files (testpage.mdx and img01.jpg) are both located directly inside the /pages folder.

**Comment by sebastian-1783** [comment]
I just checked what the HTML output in the browser looks like:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/2191378/197352970-7fc876d1-1608-40f2-9bdf-f951455db264.png">

The `src` attribute of the image tag is set to a strange value `[object Object]`

**Comment by christian-hackyourshack** [comment]
I have seen that before, it means the plugin is active, but the injected import is not resolved but evaluated as is. I try to remember what caused this. I will later on try to reproduce it on my side (I usually move my markdown files outside the pages directory and use the pages only for definition of the routing). In the meantime, you could try the latest (today's) version of the plugin 0.6.0

**Comment by sebastian-1783** [comment]
Thanks a lot!

I quickly updated to version 0.6.0, the error still persists.

I also tried the plugin inside a MDX blog page which is located outside of the /pages folder (in /data/blog/). The error is the same, the image is not displayed on the blog page as well.

**Comment by christian-hackyourshack** [comment]
I can't reproduce it locally or in StackBlitz, maybe you can create a reproduction scenario in StackBlitz?

Mine looks like this and it works:
https://stackblitz.com/edit/github-t6zkpn?file=src/pages/test.mdx

![image](https://user-images.githubusercontent.com/94894037/197356419-3c1af8d9-034d-4bfb-bcf2-b78149141687.png)

**Comment by sebastian-1783** [comment]
Ok, I tried (have never used StackBlitz before) -> I connected my repository in StackBlitz but unfortunately the dev web server isn't starting in StackBlitz for some other reasons (some NPM modules not being able to get installed  ...)

[https://stackblitz.com/edit/github-irwpf7](https://stackblitz.com/edit/github-irwpf7)

**Comment by christian-hackyourshack** [comment]
The issue is the @astrojs/image component. It has it's own understanding of local/remote and not for optimization images, based on the style of path, that you use. I am using it, too, but only the getPicture function and then I have implemented my own Image component around it.
My implementation is still really rough and I want to discuss it with the astro-team, because I have the impression, that I am not the only one struggling with it.

**Comment by christian-hackyourshack** [comment]
In order to find your path to a solution have a look at the code of astro-m2dx: What the transformer does is, it replaces the MDAST image node with a MDX <img src={<some import>} /> and adds the import to the MDAST. So it behaves exactly as if you would import your image in the MDX file and reference it with an <img> element.

**Comment by sebastian-1783** [comment]
Yes, the transformation logic of astro-m2dx is quite clear to me - I understand how the normal MD image syntax (in case of relative image paths) is transformed to an import / <img>-based MDX syntax. 
However what I do not understand is how this is interfering with the @astrojs/image component to produce the error I see

**Comment by sebastian-1783** [comment]
So if there is an option to propose a change to @astrojs/image to make it compatible with astro-m2dx this would help a lot ...

**Comment by christian-hackyourshack** [comment]
Hi Sebastian, the maintainers of @astrojs/image are very approachable and open for suggestions. So, if you know what you would need, you can always ask them. If it is something I can provide as small 'magic' automated transformation in the input pipeline, I am happy to help. At the moment I have no clear idea yet, what I would expect from the Image component as general solution. Hence I have my own wrapping Image components and they sometimes even differ from Layout to Layout.

I assume the general approach with astro-m2dx and @astrojs/image is now clear and solved (wenn auch nicht sooo automagisch, wie man sich das erträumt...), hence I will close this issue now.

Happy hacking,
Christian
